# Generated by Django 5.2.4 on 2025-07-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=200000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
