# Generated by Django 5.0.7 on 2025-07-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_style',
            field=models.CharField(default='style1', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_summary',
            field=models.CharField(default='style1', max_length=20),
            preserve_default=False,
        ),
    ]
