# Generated by Django 5.0.7 on 2025-07-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_style_post_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text_field',
            field=models.TextField(default='Text field', max_length=200000),
            preserve_default=False,
        ),
    ]
