# Generated by Django 5.2.4 on 2025-07-29 17:59

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_post_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text_field',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=255),
        ),
    ]
